
default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :deploy do

    # Signing
    match(readonly: true)

    sh "pod install"
    # Build
    sh "flutter build ios --release --flavor prod --no-tree-shake-icons --no-pub"

    # .ipa 생성
    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "prod",
      export_method: "app-store",
      clean: true,
      xcargs: "-allowProvisioningUpdates"
    )

    # Deploy
    upload_to_testflight
  end
end
