
default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :deploy do

    setup_circle_ci

    # Signing
    match(readonly: true)

    # Build
    flutter_build_ios

    # .ipa 생성
    build_ios_app(
      workspace: "Runner.xcworkspace",
      scheme: "prod",
      export_method: "app-store",
      clean: true,
      xcargs: "-allowProvisioningUpdates",
      build_path: "build",
      output_directory: "output",
    )

    # App Store Connect API 인증 설정
    app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_KEY_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY_KEY"],
      duration: 1200,
      in_house: false
    )

    # Deploy
    upload_to_testflight(
      team_id: ENV["IOS_APPSTORE_TEAM_ID"],
      team_name: ENV["IOS_APPSTORE_ITC_TEAM_ID"],
      apple_id: ENV["IOS_APPLE_ID"],
      skip_waiting_for_build_processing: true
    )
  end

    # Flutter build iOS
    lane :flutter_build_ios do
      sh("cd", "..")
      puts "Flutter clean"
      sh("flutter", "clean")
      puts "Flutter build iOS"
      sh("flutter", "build", "ios", "--no-codesign", "--flavor", "prod", "--release", "--no-tree-shake-icons")
    end
end
