
default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :deploy do

    # Signing
    match(readonly: true)

    # Build
    sh "flutter build ios --release --flavor prod --no-tree-shake-icons"

    # Deploy
    upload_to_testflight
  end
end
