name: 'Flutter Setup'
description: 'Setup Flutter environment with common configurations'

runs:
  using: "composite"
  steps:
    - name: Set up Homebrew
      uses: Homebrew/actions/setup-homebrew@master

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Fastlane
      shell: bash
      run: |
        brew install fastlane
        cd ios
        gem install bundler
        bundle install

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable

    - name: Flutter Setup
      shell: bash
      run: |
        flutter pub get
        flutter pub run build_runner build --delete-conflicting-outputs

    - name: Run Tests
      shell: bash
      run: flutter test

    - name: Version Update
      uses: ./.github/actions/version_update
